### ISSUE TITLE
split（）have some questions

### ISSUE THREAD

**Issue by vvwin** [ruiqiRichard/EEGViT#1]
![image](https://github.com/ruiqiRichard/EEGViT/assets/65641042/4138288a-4af5-4d33-9617-52ef66ac2864)

**Comment by ModeEric** [comment]
From your code it seems like the version of split you are trying to use is from pyspark, not the version from the helper_functions.py folder in this repo. Make sure that the correct version is imported and let me know if any other questions arise.
